### ISSUE TITLE
Joining chat rooms fails with "Verfication Failed!"

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#556] opened 2017-11-08 13:38 UTC
```
--> POST https://tumcabe.in.tum.de/Api/chat/rooms/ http/1.1
Content-Type: application/json; charset=UTF-8
Content-Length: 445
X-DEVICE-ID: 77720654-30bf-4627-8260-22d3f53d10d0
User-Agent: TCA Client 1.4.10-dev/99999
X-ANDROID-VERSION: 7.0
X-APP-VERSION: 1.4.10-dev
Host: tumcabe.in.tum.de
Connection: Keep-Alive
Accept-Encoding: gzip
Cookie: TCAP=<REDACTED>
{"data":{"id":0,"members":-1,"name":"17W:Ausgewählte Themen aus dem Bereich Datenbanken und Informationssysteme: Data Processing On Modern Hardware (IN3100)"},"date":"Wed Nov 08 14:24:05 GMT+01:00 2017","member":36,"rand":"ht32jh7731qtjl80d8800n1r5e","signature":"<REDACTED>"}
--> END POST (445-byte body)
<-- 401 Unauthorized https://tumcabe.in.tum.de/Api/chat/rooms/ (0ms)
Server: nginx
Date: Wed, 08 Nov 2017 13:24:04 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache, must-revalidate
Expires: Mon, 26 Jul 1997 05:00:00 GMT
{"error":"Verfication Failed!"}
<-- END HTTP (31-byte body)
```

Maybe this is because of the ObfuscatedIDs? @kordianbruck what do you think?

**Comment by kordianbruck** [comment] 2017-11-08 16:42
No, this is because your activation failed with TUMonline and the public key for communication with tumcabe was not marked as valid.

So whenever the token activation fails, we cannot confirm that the private key actually is the user.

**Comment by pfent** [comment] 2017-11-08 18:06
nvm then

**Comment by kordianbruck** [comment] 2017-11-09 00:57
I've just reproduced this. No clue why this is happening then.

**Comment by kordianbruck** [comment] 2017-11-09 00:57
We really need unit tests for this!

**Comment by kordianbruck** [comment] 2018-02-16 16:01
Actually this should no longer happen, as we test this during the wizzard / setup

**Closed by kordianbruck** 2018-02-16 16:01 UTC
Labels: Bug, good first issue
