### ISSUE TITLE
Crash after upgrade to v1.5.2

### ISSUE THREAD

**Issue by xsrf** [TCA-Team/TumCampusApp#667] opened 2018-02-14 17:29 UTC
## Problem

Since upgrading to v1.5.2 the app crashes all the time when I open it. It also crashes from time to time while the app is not even used at all. Chat was never used before.

## Stacktrace

![2018-02-14 18_24_22-screenshot_20180214-174434 png - fotos](https://user-images.githubusercontent.com/8081353/36218352-5b316252-11b4-11e8-9dc8-eeff02f64492.png)

### Environment
* Phone: Nexus 7 (2013)
* OS version: 6.0.1
* TUM Campus App version: v1.5.2
* Language: de

**Comment by kordianbruck** [comment] 2018-02-15 07:07
@OliHalu seems to happen with the chat sending in the background. Can you take a look?

**Comment by OliHalu** [comment] 2018-02-15 07:59
@kordianbruck sure, I'll take a look later today

**Comment by OliHalu** [comment] 2018-02-15 17:04
@xsrf @kordianbruck So far I couldn't encounter the problem with Samsung Galaxy S7 OS version 7.0 and Nexus 9 OS version 4.4 (Emulator).  No crashes at all. In the stacktrace it sais 

> ...column 'msg_id' does not exist at..  

what is weird since the column 'msg_id' is defined in the ChatMessage model class and therefore should exist in the database.

**Comment by kordianbruck** [comment] 2018-02-16 09:55
@OliHalu did you try to clear your data? So on an empty installation if the tables are empty?

**Comment by OliHalu** [comment] 2018-02-16 13:27
@kordianbruck yes I deleted the data via preferences in the app itself and via Android app settings. But I encounter no crashes at all. Everything works fine.

**Comment by kordianbruck** [comment] 2018-02-16 16:38
So as far as I recall how XSRF installed the app, was that he had the v1.5.1 installed previously and upgraded. Maybe there is the problem there? Is the migration script faulty? @OliHalu

**Comment by OliHalu** [comment] 2018-02-16 17:18
@kordianbruck Only thing I could imagine is that upgrading from v1.5.1 to v1.5.2 might be problematic because in v1.5.2 the chat_message and unsent_chat_message tables are merged. The migration script is doing the chat migrations for the already merged table. Maybe we have to add migration for the old app version which has two tables belonging to the chat?

**Comment by anselm92** [comment] 2018-02-16 19:24
@kordianbruck how did he install 1.5.2?

**Comment by xsrf** [comment] 2018-02-16 19:26
he updated via google play ;)

**Comment by anselm92** [comment] 2018-02-16 19:27
@kordianbruck or @xsrf can you send me the beta link? so i can enroll and test

**Comment by kordianbruck** [comment] 2018-02-16 21:32
You can find it on the facebook page, or it also should be at the very bottom in the play store

**Comment by kordianbruck** [comment] 2018-02-19 15:25
So I can reproduce this. 
- Install version 1.5.1
- Run App and set it up
- Install beta/or 1.5.2
- App crashes on every start.

@anselm92 ideas?

**Comment by kordianbruck** [comment] 2018-02-19 15:55
>"IF NOT EXISTS" statement does not work in some versions of Android, specifically 4.0.x versions. At least when creating virtual tables. It has crashed one of my published apps several times in versions 4.0.4 and 4.0.3. My app works properly in versions 4+ but crashes as soon as it uses DB only in these specific versions.<

I hate Android & SQLite

**Comment by kordianbruck** [comment] 2018-02-19 16:11
Ok, still not fixed. I can't tell why, but apparently the DB is not created correctly.

**Comment by kordianbruck** [comment] 2018-02-19 16:26
@OliHalu 
`ChatRoomDbRow` looks really fishy to me. Why does it have the following as a class member?! There is no comment, no nothing?

```
    var timestamp: String? = ""
    var text: String? = ""
```

**Comment by kordianbruck** [comment] 2018-02-20 09:19
```
02-20 10:18:42.356 31346-1215/de.tum.in.tumcampus E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                    Process: de.tum.in.tumcampus, PID: 31346
                                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                        at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                                        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                        at java.lang.Thread.run(Thread.java:761)
                                                                     Caused by: android.database.sqlite.SQLiteException: table chat_room has no column named timestamp (code 1): , while compiling: INSERT OR REPLACE INTO `chat_room`(`timestamp`,`text`,`room`,`name`,`semester`,`semester_id`,`joined`,`_id`,`contributor`,`members`) VALUES (?,?,?,?,?,?,?,?,?,?)
                                                                        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                                        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                                        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                        at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:996)
                                                                        at android.arch.persistence.db.framework.FrameworkSQLiteDatabase.compileStatement(FrameworkSQLiteDatabase.java:62)
                                                                        at android.arch.persistence.room.RoomDatabase.compileStatement(RoomDatabase.java:204)
                                                                        at android.arch.persistence.room.SharedSQLiteStatement.createNewStatement(SharedSQLiteStatement.java:65)
                                                                        at android.arch.persistence.room.SharedSQLiteStatement.getStmt(SharedSQLiteStatement.java:72)
                                                                        at android.arch.persistence.room.SharedSQLiteStatement.acquire(SharedSQLiteStatement.java:87)
                                                                        at android.arch.persistence.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:61)
                                                                        at de.tum.in.tumcampusapp.database.dao.ChatRoomDao_Impl.replaceRoom(ChatRoomDao_Impl.java:129)
                                                                        at de.tum.in.tumcampusapp.managers.ChatRoomManager.replaceIntoRooms(ChatRoomManager.java:112)
                                                                        at de.tum.in.tumcampusapp.activities.wizard.WizNavExtrasActivity.onLoadInBackground(WizNavExtrasActivity.java:148)
                                                                        at de.tum.in.tumcampusapp.activities.wizard.WizNavExtrasActivity.onLoadInBackground(WizNavExtrasActivity.java:32)
                                                                        at de.tum.in.tumcampusapp.activities.generic.ActivityForLoadingInBackground$1.doInBackground(ActivityForLoadingInBackground.java:67)
                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                        at java.lang.Thread.run(Thread.java:761) 
```

**Closed** 2018-02-20 10:57 UTC
Labels: Bug, High Priority
