### ISSUE TITLE
Chat PKI confirmation leads to crash when key is not enabled

### ISSUE THREAD

**Issue by TCA-Team** [TCA-Team/TumCampusApp#357] opened 2016-01-27 16:46 UTC
After upgrading to 6.0.1 and testing TCA there is a crash upon the chat key verification.

**Comment by kordianbruck** [comment] 2016-01-27 16:48
Is this with the latest release from the play store or the dev branch?

**Comment by TCA-Team** [comment] 2016-01-27 16:53
The one that is available on github (latest) ; If I'm not mistaken it happened when I clicked next, while the permission was not granted yet (I still had to click the link in the mail).

**Comment by TCA-Team** [comment] 2016-01-27 16:55
There is probably no bug report, since I deactivated it for testing purposes previously

**Comment by kordianbruck** [comment] 2016-01-27 16:57
Right, this is probably the same bug that @pfent has mentioned in #338

**Comment by kordianbruck** [comment] 2016-06-09 13:03
Dupe of #339

**Closed by kordianbruck** 2016-06-09 13:03 UTC
Labels: Bug, Duplicate
