### ISSUE TITLE
Indoor Navigation (initial: FMI)

### ISSUE THREAD

**Issue by nilstk** [TCA-Team/TumCampusApp#353] opened 2015-12-28 07:50 UTC
https://c3nav.de/?o=wcc&d=catering
You get really lost here often :)

We need something similar for 1st term students. Anyone up for integrating it for FMI maybe? (Others may follow if used frequently)

**Comment by kordianbruck** [comment] 2015-12-29 00:00
Duplicate of #313.

Surely a good idea and we can work on this as soon as we have the big issues out of the way.

**Closed by kordianbruck** 2015-12-29 00:00 UTC
